### ISSUE TITLE
I have tested with 16:10 screen display, it works!

### ISSUE THREAD

**Issue by DoubleTrust** [Lyall/WukongTweak#1]
Thank you so much for your MOD, though FOV is a bit narrower

**Comment by therocketpunch** [comment]
What number of FOV is good? I read some guy said in the guide that 120 FOV is good.

**Comment by DoubleTrust** [comment]
> What number for FOV is good? I read some guy said in the guide that 120 FOV is good.

I need to test it tonight. using this MOD only will make fov narrower a bit. need another tool to make it broader @therocketpunch
