### ISSUE TITLE
Can I use this instead of the mod "Better shadows tweak - force Unreal Virtual shadows" 

### ISSUE THREAD

**Issue by grasum** [Lyall/WukongTweak#12]
If I enable Virtual Shadow Maps in your WukonTweaks.ini can I skip using the mod? Or I can use both at the same time with now issues?
https://www.nexusmods.com/blackmythwukong/mods/22?tab=description

**Comment by Lyall** [comment]
Yes you can skip using the mod if you enable it in WukongTweak.
