### ISSUE TITLE
[Feature Request] Set RT quality individually for : reflections, shadows, global illumination

### ISSUE THREAD

**Issue by Foul-Tarnished** [Lyall/WukongTweak#13]
- The RT low preset use a mix of cubemaps and SSR instead of RT reflections, but they look good (even though not accurate)
- The RT medium preset use real RT reflections but these are extremely low resolution and pixelated.
- The RT Ultra preset is the only one with good looking *and* accurate RT reflections

I ask if we could force the reflections of the RT low preset on the medium preset
(not really to save FPS, but to have good looking reflections, albeit not accurate)

Or even better if we could decouple quality for reflections, shadows, global illumination and set the preset for each of them individually.

**RT Low** (looks ok)
<img src="https://github.com/user-attachments/assets/feb8b101-838c-4a8c-b936-1a3bf3c5a482" width="50%"/>

**RT Medium** (looks awful)
<img src="https://github.com/user-attachments/assets/36f77593-4640-4d57-bc14-cbe4ed8475e3" width="50%"/>

**RT Ultra** (looks great)
<img src="https://github.com/user-attachments/assets/572d44c8-c877-44c2-b93a-50f0ee8dd9fc" width="50%"/>

Please look these in fullscreen, see how medium look soooo bad

I find RT Ultra too hard to run, RT low look too bad (shadows quality drop at short distance), and RT medium has awful reflections.
Also the FPS difference between RT low and medium is small on my 4080

(These screenshots were made using DSR 4x (4K on 1080p monitor) with DLSS performance and DLSS frame-gen)

**Comment by Lyall** [comment]
I believe I have the list of CVars that are applied at the ray tracing presets. This should make it clear what is changing on the 3 quality levels. 

https://gist.github.com/Lyall/d7f9c5bf932797c11478216a073dce69#file-rt-ini

**Comment by Foul-Tarnished** [comment]
Where should theye be entered ? engine.ini, scalability.ini ? I don't
remember seeing a rt.ini

**Comment by Foul-Tarnished** [comment]
> I believe I have the list of CVars that are applied at the ray tracing presets. This should make it clear what is changing on the 3 quality levels.
> 
> https://gist.github.com/Lyall/d7f9c5bf932797c11478216a073dce69#file-rt-ini

```
[RayTracingQuality@2]
r.RayTracing.Reflections=0
```
This in Scalability.ini let me have the fake reflections on RT medium, instead of the blurry ones.
Thanks !

**Comment by Lyall** [comment]
Glad it was helpful. I'll close this issue for now since this isn't something I'd add to WukongTweak directly given they can be overridden in `Engine.ini` or `Scalability.ini`.
