### ISSUE TITLE
Developer Console crashes game? (In new update)

### ISSUE THREAD

**Issue by Wobbledongle101** [Lyall/WukongTweak#16]
In the new update the game crashes, and I think the cause is developer console being turned ON. Turning it off (false) stopped the game from crashing.

**Comment by Mario-Chapa** [comment]
I can confirm its the console, setting `[Developer Console]` to false fixed the crashing at startup for me as well

**Comment by Lyall** [comment]
Is this crashing still happening with v0.8.4?

**Comment by vagabondHustler** [comment]
Seems to be fixed, just updated from 0.8.2_test i think to latest
