### ISSUE TITLE
Black Myth: Wukong 1.0.8.14860 Patch  (latest) with mod pack causes crash from Homescreen

### ISSUE THREAD

**Issue by CodyJReed** [Lyall/WukongTweak#17]
`WukongTweak` is the only mod running with the current build

**Comment by Lyall** [comment]
Please post your `WukongTweak.log` file.

**Comment by bunny-ball** [comment]
I meet the same crash issue, here is my log attached

[WukongTweak.log](https://github.com/user-attachments/files/16805300/WukongTweak.log)

**Comment by Lyall** [comment]
> I meet the same crash issue, here is my log attached
> 
> [WukongTweak.log](https://github.com/user-attachments/files/16805300/WukongTweak.log)

You're still using v0.8.3 of WukongTweak. You need to use v0.8.4 which was released earlier today.

**Comment by bunny-ball** [comment]
> > I meet the same crash issue, here is my log attached
> > [WukongTweak.log](https://github.com/user-attachments/files/16805300/WukongTweak.log)
> 
> You're still using v0.8.3 of WukongTweak. You need to use v0.8.4 which was released earlier today.

There's no crush problem with the latest version, thank you!
