### ISSUE TITLE
Epic Games

### ISSUE THREAD

**Issue by bybrii** [Lyall/WukongTweak#22]
Someone know if this work for epic games also? I tryied a lot of things but not working. Also I searched info and nothing founded.

**Comment by kreviuz** [comment]
Works fine for me. Just check your installation directory and put those files in BlackMythWukong\b1\Binaries\Win64 folder instead of steam path from description.

**Comment by bybrii** [comment]
> Works fine for me. Just check your installation directory and put those files in BlackMythWukong\b1\Binaries\Win64 folder instead of steam path from description.

I already tryied that, putting the whole folder or the files without folder. Nothing worked. And the console is working for you?

**Comment by Lyall** [comment]
Can you take a screenshot of the contents of the folder `b1\Binaries\Win64`. You'll need `dsound.dll`, `WukongTweak.asi` and `WukongTweak.ini` next to `b1-Win64-Shipping.exe`

**Comment by bybrii** [comment]
![image](https://github.com/user-attachments/assets/bb5c5023-eb7c-4f2d-b84d-f2291c3aecf4)
![image](https://github.com/user-attachments/assets/d420ac64-1c28-4ce6-ac99-e00220866acb)
![image](https://github.com/user-attachments/assets/858a67b6-0dc1-4b5d-adca-c0b095288363)
I have the files like in the third photo bc is what i understood about the second image.

**Comment by Lyall** [comment]
You've downloaded the source code, not a compiled release. Go to [this page] (https://github.com/Lyall/WukongTweak/releases) and download the latest release version.
![image](https://github.com/user-attachments/assets/c4eb7ff7-1466-4acd-8f6c-a032d390dc70)

**Comment by bybrii** [comment]
omg thank you so much, i'm new on this things like mods and github. idk how i ended dw the source but thanj you one more time
