### ISSUE TITLE
VSM Shadows do not work

### ISSUE THREAD

**Issue by phonyprince** [Lyall/WukongTweak#23]
Everything works, except for some reason, these lines in the "wukongTweak.ini" doesn't change anything:

[Virtual Shadow Maps]
; Set to true to enable virtual shadow maps.
; These can produce much higher quality non-RT shadows but may cause some visual errors.
; Game default = false
Enabled = true

However, adding these lines in the "engine.ini" allow VSMs to work perfectly:

[SystemSettings]
r.Shadow.Virtual.Enable=1

Unfortunately, using the "wukongTweaks.ini" Mod prevents the modifications on the "engine.ini", thus we can't mix both solutions and I have to delete the Tweak mod for the engine.ini to take over.

**Comment by Lyall** [comment]
It seems to work fine for me.

![image](https://github.com/user-attachments/assets/d3df68ac-8e78-4ab7-8ad5-e360211ff5ca)

 I can change it to only apply when VSMs are enabled though. That way you can disable it in `WukongTweak.ini` and do it in `Engine.ini` instead.

**Comment by Lyall** [comment]
That change is now present in v0.8.5.

**Comment by phonyprince** [comment]
Hello Lyall,
Since the 0.8.5 version the VSM shadows work again in the combined use of your Mod and the tweak of "engine.ini".
I don't know if we still even need to touch the engine.ini file for everything to work, but at least now we can have everything: sharpness and other effects tweaking, while having high quality Lumen shadows.
Thank you for the amazing work and allowing us to enjoy the game in the best possible set up !
