### ISSUE TITLE
Can we add configuration of  r.Lumen.Reflections.DiffuseBoost ?

### ISSUE THREAD

**Issue by MarxistZ** [Lyall/WukongTweak#4]
Hi Lyall,

Thank you for your fantastic Wukong mod! I’ve noticed some issues with lighting quality in darker scenes, especially in Chapter 1. It seems adjusting the r.Lumen.Reflections.DiffuseBoost setting could improve the lighting based on community suggestions.

I tried using Unreal Engine 5 Unlocker  (UUU5) to tweak this, but seems like it conflicts with your mod’s DLL. Since I’m not familiar with C++ or your toolchain, could you consider adding an option to adjust the r.Lumen.Reflections.DiffuseBoost setting directly within the mod? This would make it easier to fine-tune the lighting without third-party tools.

Thanks for your consideration!

Best regards,

**Comment by Lyall** [comment]
`r.Lumen.Reflections.DiffuseBoost` is not a valid CVar in this version of Unreal Engine. I have dumped all available [CVars here](https://github.com/Lyall/WukongTweak/blob/master/CVarDump.txt).
