### ISSUE TITLE
Can we add configuration of r.Shadow.Virtual.Enable=1?

### ISSUE THREAD

**Issue by Egolas** [Lyall/WukongTweak#7]
There's a community [shadow fix](https://www.nexusmods.com/blackmythwukong/mods/22) to use the UE5 Virtual Shadowmap instead of the in-game shabby shadow maps.

Another great fix [BMWK - SPF](https://www.nexusmods.com/blackmythwukong/mods/13) is incompatible with engine.ini tweaks but is compatible with your work.

Could you consider adding an option to adjust the 'r.Shadow.Virtual.Enable' setting to benefit from yours and the mods mentioned above?

**Comment by Lyall** [comment]
Added in v0.8.2
